version: "2"

services:
  cassandra:
    image: cassandra:3
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_USER=kong
      - CASSANDRA_PASSWORD=kong
      - CASSANDRA_PASSWORD_SEEDER=yes
  kong:
    image: kong:2.2.1-alpine
    container_name: kong
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8002:8002"
      - "8444:8444"
      - "7946:7946"
      - "7946:7946/udp"
    links:
      - cassandra:cassandra
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=cassandra
      - KONG_CASSANDRA_PASSWORD=kong
      - KONG_MIGRATE=yes
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    depends_on:
      - cassandra
    restart: always
    command: ["/bin/bash", "-c", " while ! nc cassandra 9042; do sleep 5; done && kong migrations bootstrap && kong start"]
  kong-ui:
    image: pocketdigi/kong-admin-ui:0.4.3
    container_name: kong-admin-ui
    ports:
      - "8899:80"
